---
- name: Manage DNS settings on Sophos Firewall
  hosts: testfirewalls
  gather_facts: false

  vars_files:
    - vars/secrets.yml  # Path to your secrets file

  tasks:
    # Task to update DNS settings on the firewall
    - name: Update DNS settings on Firewall
      sophos.sophos_firewall.sfos_dns:
        username: "{{ username }}"
        password: "{{ password }}"
        hostname: "{{ inventory_hostname }}"
        port: 4444
        verify: false
        ipv4_settings:
          dns_source: Static
          dns1: 4.2.2.1
          dns2: 8.8.8.8
          dns3: 1.1.1.1
        state: present
      delegate_to: localhost
