---
- name: Manage IP Host and Network Host on Sophos Firewall
  hosts: testfirewalls
  gather_facts: false

  vars_files:
    - vars/secrets.yml  # Path to your secrets file

  tasks:
    # Task to read IP Host data from CSV
    - name: Read IP Host configuration from CSV
      community.general.read_csv:
        path: csvfiles/iphosts.csv  # Path to your CSV file
        delimiter: ','
      register: firewall_data_ip

    # Task to create IP Hosts on the firewall
    - name: Create IP Hosts on Firewall
      sophos.sophos_firewall.sfos_ip_host:
        username: "{{ username }}"
        password: "{{ password }}"
        hostname: "{{ inventory_hostname }}"
        port: 4444
        verify: false
        name: "{{ item.name }}"
        ip_address: "{{ item.ip_address }}"
        state: present
      loop: "{{ firewall_data_ip.list }}"
      loop_control:
        loop_var: item
      delegate_to: localhost

    # Task to read Network Host data from CSV
    - name: Read Network Host configuration from CSV
      community.general.read_csv:
        path: csvfiles/networkhosts.csv  # Path to your CSV file
        delimiter: ','
      register: firewall_data_network

    # Task to create Network Hosts on the firewall
    - name: Create Network Hosts on Firewall
      sophos.sophos_firewall.sfos_ip_host:
        username: "{{ username }}"
        password: "{{ password }}"
        hostname: "{{ inventory_hostname }}"
        port: 4444
        verify: false
        name: "{{ item.name }}"
        network: "{{ item.network }}"
        mask: "{{ item.subnet }}"
        host_type: network
        state: present
      loop: "{{ firewall_data_network.list }}"
      loop_control:
        loop_var: item
      delegate_to: localhost


  # Task to read Network Host  data from CSV
    - name: Read Network Host configuration from CSV
      community.general.read_csv:
        path: csvfiles/iprangehosts.csv  # Path to your CSV file
        delimiter: ','
      register: firewall_data_range

    # Task to create Network Hosts on the firewall
    - name: Create Network Hosts on Firewall
      sophos.sophos_firewall.sfos_ip_host:
        username: "{{ username }}"
        password: "{{ password }}"
        hostname: "{{ inventory_hostname }}"
        port: 4444
        verify: false
        name: "{{ item.name }}"
        start_ip: "{{ item.start_ip }}"
        end_ip: "{{ item.end_ip }}"
        host_type: range
        state: present
      loop: "{{ firewall_data_range.list }}"
      loop_control:
        loop_var: item
      delegate_to: localhost

       # Task to read IP Host data from CSV
    - name: Read IP Host configuration from CSV
      community.general.read_csv:
        path: csvfiles/fqdnhosts.csv  # Path to your CSV file
        delimiter: ','
      register: firewall_data_fqdn

 