---
- name: Manage IP Host and Network Host on Sophos Firewall
  hosts: testfirewalls
  gather_facts: false

  vars_files:
    - vars/secrets.yml  # Path to your secrets file

  tasks:
    # Task to read IP Host data from CSV
    - name: Read IP Host configuration from CSV
      community.general.read_csv:
        path: csvfiles/users.csv  # Path to your CSV file
        delimiter: ','
      register: firewall_data_users


    # Task to create Network Hosts on the firewall
    - name: Create Network Hosts on Firewall
      sophos.sophos_firewall.sfos_user:
        username: "{{ username }}"
        password: "{{ password }}"
        hostname: "{{ inventory_hostname }}"
        port: 4444
        verify: false
        name: "{{ item.name }}"
        user: "{{ item.username }}"
        description: ""
        user_password: "{{ item.user_pwd}}"
        user_type: "{{item.user_type}}"
        group: "{{item.group}}"
        email: "{{item.email}}"
        access_time_policy: "{{item.access_time_policy}}"
        applianceaccess_schedule: "{{item.applianceaccess_schedule}}"
        clientless_policy: "{{item.clientless_policy}}"
        sslvpn_policy: "{{item.sslvpn_policy}}"
        simultaneous_logins: "{{item.simultaneous_logins}}"
        quarantine_digest: "{{item.quarantine_digest }}"
        pptp: "{{item.pptp}}"
        l2tp: "{{item.l2tp }}"
        surfingquota_policy: "{{item.surfingquota_policy}}"
        state: present
      loop: "{{ firewall_data_users.list }}"
      loop_control:
        loop_var: item
      delegate_to: localhost


 